### ISSUE TITLE
Bot is not uploading

### ISSUE THREAD

**Issue by Argurotoxus** [aytiel/PHTM-b0t#7]
I'm not sure what the issue is at this point. I'm getting the following error in the bot script:

Ignoring exception in command upload:                                            Traceback (most recent call last):                                                 File "C:\Users\Ryan\AppData\Local\Programs\Python\Python36\lib\site-packages\d iscord\ext\commands\core.py", line 62, in wrapped                                    ret = await coro(*args, **kwargs)                                              File "E:\Downloads\PHTM-b0t-master\PHTM-b0t-master\GW2LogBot\cogs\arcdps.py",  line 103, in upload                                                                  await ctx.message.delete()                                                     File "C:\Users\Ryan\AppData\Local\Programs\Python\Python36\lib\site-packages\d iscord\message.py", line 549, in delete                                              await self._state.http.delete_message(self.channel.id, self.id)                File "C:\Users\Ryan\AppData\Local\Programs\Python\Python36\lib\site-packages\d iscord\http.py", line 212, in request                                                raise NotFound(r, data)                                                      discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message
--

And then just nothing happens.

**Comment by aytiel** [comment]
Issue resolved via Discord
